### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by anishkny** [anishkny/realworld-dynamodb-lambda#2]
**Articles**

- [ ] GET - Feed
- [ ] GET - All articles
- [ ] GET - Articles by author
- [ ] GET - Articles favorited by username
- [ ] GET - Articles by tag
- [ ] POST - Create article
- [ ] GET - Single article by slug
- [ ] DEL - Delete article
- [ ] PUT - Update article
- [ ] POST - Favorite article
- [ ] DEL - Unfavorite article

**Auth**

- [x] POST - Login
- [ ] POST - Login and remember token
- [ ] POST - Register
- [ ] GET - Get current user
- [ ] PUT - Update user

**Comments**

- [ ] GET - All comments for article
- [ ] POST - Create comment for article
- [ ] DEL - Delete comment

**Profile**

- [ ] GET - Profile
- [ ] POST - Follow profile
- [ ] DEL - Unfollow profile

**Tags**

- [ ] GET - Get all tags

**Comment by anishkny** [comment]
Closing in favor of [Project v1.0](https://github.com/anishkny/realworld-dynamodb-lambda/projects/1)
